# Site settings
title: Aryee Lab Homepage
email: aryee.martin@mgh.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  Martin Aryee Lab
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aryeelab.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  aryeelab

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
